version: '3'

volumes:
  postgres_data:
    driver: local

networks:
  quotesc-net:
    driver: bridge

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: quotesc
      POSTGRES_USER: app
      POSTGRES_PASSWORD: passme
    ports:
      - 5432:5432
    networks:
      - quotesc-net

  quotesc-build:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    networks:
      - quotesc-net
    ports:
      - 8080:8080

  quotesc:
    image: quotesc-backend:latest
    networks:
      - quotesc-net
    environment:
      - OIDC_SERVER=https://auth.obyoxion.at/auth/realms/quotesc
      - OIDC_CLIENT_ID=quotesc-backend
      - OIDC_SECRET=cf6a353d9-df3b-4503-8292-8e1a6bef296f
    ports:
      - 8080:8080