version: '3'

volumes:
  keycloak_data:
    driver: local
  quotesc_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge

services:
  keycloak_db:
    image: postgres
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: app
      POSTGRES_PASSWORD: passme
    networks:
      - keycloak_network
  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak_db
      DB_DATABASE: keycloak
      DB_USER: app
      DB_SCHEMA: public
      DB_PASSWORD: passme
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8081:8080
    networks:
      - keycloak_network
  quotesc_db:
    image: postgres
    volumes:
      - quotesc_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: quotesc
      POSTGRES_USER: app
      POSTGRES_PASSWORD: passme
    ports:
      - 5432:5432