name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Package
      run: |
        ./mvnw package
    - uses: azure/docker-login@v1
      with:
        login-server: registry.obyoxion.at
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build -f src/main/docker/Dockerfile.jvm -t registry.obyoxion.at/quotesc-backend .
        docker push registry.obyoxion.at/quotesc-backend:latest
